# Generated by Django 5.1.1 on 2025-04-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="vectorImg",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
